version: "3.7"

services:    
  sso:
    image: quay.io/keycloak/keycloak:latest
    #22.0.1
    container_name: "keycloak"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
      - PROXY_ADDRESS_FORWARDING=true
      #- VIRTUAL_HOST=dev-keycloak.mydomain.com
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=localhost
      - KC_DB_PASSWORD=changeme
    networks:
      - priv-net-4
    ports:
      - 7076:8080

  database:
    image: postgres:14-alpine
    container_name: "kcgres"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DATABASE=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5439:5432
    networks:
      - priv-net-4

  proxy:
    image: nginxproxy/nginx-proxy
    container_name: "nginx"
    ports:
      - "8443:443"
      - "7077:80"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - priv-net-4

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: "acme-proxy"
    environment:
      - DEFAULT_EMAIL=callanankids@gmail.com
      - ACME_PREFERRED_CHAIN="ISRG Root X1"
    volumes_from:
      - proxy
    volumes:
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - priv-net-4

networks:
  priv-net-4:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.4.0/28
      
networks:
  internal:
    driver: bridge
    driver_opts:
      # Openstack spezifisch, kann auf 1500 gelassen werden wenn ihr auf
      # Bare Metal lauft. 
      com.docker.network.driver.mtu: 1450

volumes:
  postgres_data:
  conf:
  vhost:
  html:
  certs:
  acme:

