version: '3.9'

services:
  pgcloak:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5439:5432
    networks:
      - priv-net-5

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: pgcloak
      DB_DATABASE: keycloakdb
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      #KEYCLOAK_LOG_LEVEL: TRACE
      #ROOT_LOG_LEVEL: TRACE
      #BITNAME_DEBUG: 'true'
    ports:
      - 7077:8080
      - 8443:8443
    depends_on:
      - pgcloak
    networks:
      - priv-net-5

networks:
  priv-net-5:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.5.0/28