version: '3.7'

services:
  zookeeper:
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:7.5.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:22181
    networks:
      priv-kafka-net:
 
  kafka:
    hostname: kafka
    image: confluentinc/cp-kafka:7.5.2
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "29093:29093"
    volumes:
      - ~/kafka:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.108:22181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.108:29092, PLAINTEXT_HOST://192.168.99.108:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      priv-kafka-net:

networks:
  priv-kafka-net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.3.0/28